### ISSUE TITLE
Unable to install as a setup.py dependency

### ISSUE THREAD

**Issue by GMishx** [gfairchild/pyxDamerauLevenshtein#13]
In my project when I am trying to install `pyxDamerauLevenshtein` as a run time dependency in my setuptools' `setup.py` file I am getting following error:

```
Processing dependencies for atarashi==0.0.9

Searching for pyxDamerauLevenshtein>=1.5

Reading https://pypi.org/simple/pyxDamerauLevenshtein/

Downloading https://files.pythonhosted.org/packages/09/d8/77d02800d687ff8e12c8ec7b4ed917249fca27a1bccc6d24f0ac507a794c/pyxDamerauLevenshtein-1.5.tar.gz#sha256=00b836cdb7cff24abe20c2fdc6cdda4ac24413a82cf318c983980ce4aaec7e16

Best match: pyxDamerauLevenshtein 1.5

Processing pyxDamerauLevenshtein-1.5.tar.gz

Writing /tmp/easy_install-r1p8hre8/pyxDamerauLevenshtein-1.5/setup.cfg

Running pyxDamerauLevenshtein-1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-r1p8hre8/pyxDamerauLevenshtein-1.5/egg-dist-tmp-twm03pcs

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-r1p8hre8/pyxDamerauLevenshtein-1.5/setup.py", line 97, in <module>
    "atarashi/build_deps.py",
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "/usr/local/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/usr/local/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-r1p8hre8/pyxDamerauLevenshtein-1.5/setup.py", line 33, in finalize_options
    # Used for the long_description.  It's nice, because now 1) we have a top level
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 174, in <module>
    'build_py': BuildAtarashi,
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 415, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 657, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 704, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 749, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1060, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1072, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 676, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 702, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 887, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1155, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1141, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-r1p8hre8/pyxDamerauLevenshtein-1.5/setup.py", line 97, in <module>
    "atarashi/build_deps.py",
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "/usr/local/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/usr/local/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext

    build_ext = self.get_finalized_command('build_ext')
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-r1p8hre8/pyxDamerauLevenshtein-1.5/setup.py", line 33, in finalize_options
    # Used for the long_description.  It's nice, because now 1) we have a top level
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

But if I install it as a separate call to pip, it installs successfully:
```
# pip3 install pyxdameraulevenshtein>=1.5
pyxdameraulevenshtein 1.5 requires numpy, which is not installed.

# python3 setup.py install
...
Searching for pyxDamerauLevenshtein==1.5
Best match: pyxDamerauLevenshtein 1.5
Adding pyxDamerauLevenshtein 1.5 to easy-install.pth file
...
```

setup.py I am using: [setup.py](https://gist.github.com/GMishx/739f15f743c33222438fbbdfe9813caf)

**Comment by gfairchild** [comment]
I *think* this is the same as #11. Can you `pip install numpy` and see if that fixes it?

**Comment by GMishx** [comment]
I also tried with that, installing numpy before calling `python3 setup.py install`, but I got the same error.

It is only solved if I run `pip3 install pyxdameraulevenshtein` before calling `python3 setup.py install`.

**Comment by gfairchild** [comment]
With a completely fresh virtual environment, does `pip install pyxdameraulevenshtein` succeed?

**Comment by GMishx** [comment]
Yes, it does.

**Comment by gfairchild** [comment]
Is there a minimal working example of your `setup.py` that you can show me so that I can test this on my end?

**Comment by GMishx** [comment]
I am working on [atarashi project](https://github.com/fossology/atarashi/). Replace the `setup.py` with this: https://gist.github.com/GMishx/739f15f743c33222438fbbdfe9813caf (as old one is not working fine)

**Comment by gfairchild** [comment]
Cool, let me play with that tomorrow and see what's going on. I'm guessing it's at least partially related to #11; there's probably something in the way I'm specifying NumPy as a dependency that should be modified.

**Comment by GMishx** [comment]
But if you see the error here:
```
File "/tmp/easy_install-r1p8hre8/pyxDamerauLevenshtein-1.5/setup.py", line 33, in finalize_options
    # Used for the long_description.  It's nice, because now 1) we have a top level
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

It treats `__builtins__` as dict. So can you try something like **Example 4** here: https://www.programcreek.com/python/example/60953/__builtin__.__NUMPY_SETUP__

**Comment by GMishx** [comment]
If it helps:
1.  [Failed docker build](https://hub.docker.com/r/gmishx/atarashi/builds/bfchfxbkbdvebjgjywtcpka/)
1.  [Success docker build](https://hub.docker.com/r/gmishx/atarashi/builds/bdagdrlwjweboskfjcatphc/)

**Comment by gfairchild** [comment]
I just modified `setup.py` a bit to actually remove some checks. I've made the decision to expect the user to explicitly install NumPy prior to installing this library. 1.5.1 is now live on PyPI. I *think* this will fix your issue. Can you try and let me know?

**Comment by cwharland** [comment]
`1.5.1` now throws

```bash
  Saved ./python-packages/pyxDamerauLevenshtein-1.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-jcqaalkp/pyxDamerauLevenshtein/setup.py", line 27, in <module>
        import numpy
    ImportError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-download-jcqaalkp/pyxDamerauLevenshtein/
make: *** [.python-packages] Error 1
Exited with code 2
```

Locking at `1.5` works for us.

**Comment by cwharland** [comment]
My naive guess would be to float a more specific version of `numpy` for `install_requires`:
https://github.com/gfairchild/pyxDamerauLevenshtein/blob/master/setup.py#L81

I'll try that out when I can.

**Comment by gfairchild** [comment]
Yeah, that's because you need to explicitly install NumPy prior to installing this library. Try this:

```
pip install numpy
pip install pyxDamerauLevenshtein
```

Turns out that trying to get `setup.py` to properly install a dependency like NumPy is a pain in the ass and requires a lot of hacks that are more brittle than I'd like.

**Comment by GMishx** [comment]
I had to make a nasty hack in [my setup.py](https://github.com/fossology/atarashi/pull/43/files#diff-2eeaed663bd0d25b7e608891384b7298) to install all dependencies using `pip` in a separate `subprocess.run` call. It is working for me now.
I can not make my `setup.py` install everything in a neat way.

**Comment by gfairchild** [comment]
Yeah, that's precisely the kind of thing I was trying to avoid in my`setup.py` as well. Why not just have a bash script install the necessary dependencies first? That's much cleaner and less brittle. I've seen other libraries do something similar to this one - just expect the user to have dependencies installed before installing the library. 

I just wish the `setup.py` framework was more flexible and handled this better. This is a really common use case, and I don't quite get why it's not possible to handle it correctly without nasty hacks.

**Comment by GMishx** [comment]
pypa guys suggested me to use [PEP 518](https://www.python.org/dev/peps/pep-0518/) but I can not make it run.
https://github.com/pypa/setuptools/issues/1478#issuecomment-433142025

**Comment by gfairchild** [comment]
I'm going to try the solution in https://github.com/kwgoodman/bottleneck/pull/203. According to PEP 518, if I'm reading it correctly, simply including a `pyproject.toml` file *should* automatically install NumPy correctly. Going to try it now.

**Comment by gfairchild** [comment]
I just created `pyproject.toml` that contains the following:

```TOML
[build-system]
requires = ["setuptools", "wheel", "numpy"]
```

This appears to be working! `pip install .` produces the following output with a completely fresh virtual environment:

```
> pip install .
Processing /Users/gfairchild/Documents/projects/pyxDamerauLevenshtein
  Installing build dependencies ... done
Collecting numpy (from pyxDamerauLevenshtein==1.5.1)
  Using cached https://files.pythonhosted.org/packages/3d/c3/a69406093c9a780a74964f41cd56b06c0346d686a9b3f392d123a663f5e0/numpy-1.15.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy, pyxDamerauLevenshtein
  Running setup.py install for pyxDamerauLevenshtein ... done
Successfully installed numpy-1.15.4 pyxDamerauLevenshtein-1.5.1
```

I didn't need to modify `setup.py` at all, which is really nice. Considering one of the first things [`setup.py`](https://github.com/gfairchild/pyxDamerauLevenshtein/blob/master/setup.py#L27) does is `import numpy`, I call this a win.

I'm gonna go ahead and push a new version, 1.5.2, that fixes this.

**Comment by gfairchild** [comment]
Ok, 1.5.2 is officially live on PyPI. `pip install pyxDamerauLevenshtein` should automatically install NumPy prior to installation.

**Comment by GMishx** [comment]
Thanks for keeping me updated. I will also try it in my project!

**Comment by GMishx** [comment]
Worked for me as well! https://github.com/fossology/atarashi/pull/48

Thank you @gfairchild and @cwharland for your time and discussion.

**Comment by GMishx** [comment]
Closing the issue as the problem is resolved.

**Comment by gfairchild** [comment]
Great! Thanks for the follow-up.
